2023-11-22 20:34:14 : DEBUG : <module> : 439 : --- Start ---
2023-11-22 20:34:14 : DEBUG : load_ui : 405 : - Load UI -
2023-11-22 20:34:14 : ERROR : <module> : 447 : Failed
2023-11-22 20:34:14 : ERROR : <module> : 448 : No section: 'tkinter'
Traceback (most recent call last):
  File "C:\Users\Ryce\Documents\GitHub\CliniClick-Hospital-Appointment-System\Experiment_Env\experiment_3.py", line 444, in <module>
    load_ui()
  File "C:\Users\Ryce\Documents\GitHub\CliniClick-Hospital-Appointment-System\Experiment_Env\experiment_3.py", line 410, in load_ui
    ROOT.title(CONFIG.get('tkinter', 'title'))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryce\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 759, in get
    d = self._unify_values(section, vars)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Ryce\AppData\Local\Programs\Python\Python312\Lib\configparser.py", line 1130, in _unify_values
    raise NoSectionError(section) from None
configparser.NoSectionError: No section: 'tkinter'
2023-11-22 20:34:14 : DEBUG : <module> : 451 : --- End ---
